import ProjectDescription
import ProjectDescriptionHelpers

let workspace = Workspace(name: "Application",
                          projects: [
                              "Projects/**"
                          ],
                          generationOptions: .options(enableAutomaticXcodeSchemes: false,
                                                      autogeneratedWorkspaceSchemes: .disabled,
                                                      renderMarkdownReadme: true))
