import ProjectDescription
import ProjectDescriptionHelpers

let workspace = Workspace(name: "Application",
                          projects: [
                              "Projects/Application",
                              "Projects/Features/**",
                              "Projects/Modules/**",
                          ],
                          generationOptions: .options(enableAutomaticXcodeSchemes: false,
                                                      autogeneratedWorkspaceSchemes: .disabled,
                                                      renderMarkdownReadme: true))
